# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Create Google Application Credential
          command: |
            echo ${GOOGLE_APPLICATION_CREDENTIALS} | base64 --decode > /tmp/client-secret.json
      # run tests!
      - run:
          name: Execute test
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /tmp/client-secret.json
          command:
            cat /dev/null | sbt test:test

      - run:
          name: Delete Google Application Credential
          when: always
          command: rm /tmp/client-secret.json
